DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id VARCHAR(50) PRIMARY KEY,
	office_id VARCHAR(50) NOT NULL,
	avatar VARCHAR(255) NOT NULL,
	nik VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(50) NOT NULL,
	phone VARCHAR(20) UNIQUE NOT NULL,
	role ENUM("user", "admin") DEFAULT "user" NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	updated_at TIMESTAMP DEFAULT now(),
	deleted_at TIMESTAMP,
	FOREIGN KEY (office_id) REFERENCES offices(id)
);