DROP TABLE IF EXISTS checkins;

CREATE TABLE checkins (
	id VARCHAR(50) PRIMARY KEY,
	attendance_id VARCHAR(50) NOT NULL,
    temprature FLOAT NOT NULL,
	is_checkins BOOLEAN DEFAULT TRUE NOT NULL,
	is_checkouts BOOLEAN DEFAULT FALSE NOT NULL,
	created_at TIMESTAMP DEFAULT NOW() NOT NULL,
	updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
	FOREIGN KEY (attendance_id) REFERENCES attendances(id)
);